controllers:
  trigger_calibration_controller:
    type: rm_calibration_controllers/JointCalibrationController
    joint: trigger_joint
    actuators: [ trigger_joint_motor ]
    search_velocity: 0.
    threshold: 0.1
    pid: { p: 0.2, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
