controllers:
  chassis_controller:
    wheel_base: 0.395
    wheel_track: 0.380
    power_coeff: 2.2
    twist_angular: 0.5233
    pid_follow: { p: 5, i: 0, d: 0.8, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
