%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-robot-state-controller
Version:        0.1.1
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS robot_state_controller package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-controller-interface
Requires:       ros-noetic-hardware-interface
Requires:       ros-noetic-kdl-parser
Requires:       ros-noetic-pluginlib
Requires:       ros-noetic-realtime-tools
Requires:       ros-noetic-rm-common
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-roslint
Requires:       ros-noetic-tf2-kdl
Requires:       ros-noetic-tf2-ros
Requires:       ros-noetic-urdf
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-controller-interface
BuildRequires:  ros-noetic-hardware-interface
BuildRequires:  ros-noetic-kdl-parser
BuildRequires:  ros-noetic-pluginlib
BuildRequires:  ros-noetic-realtime-tools
BuildRequires:  ros-noetic-rm-common
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-roslint
BuildRequires:  ros-noetic-tf2-kdl
BuildRequires:  ros-noetic-tf2-ros
BuildRequires:  ros-noetic-urdf
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A template for ROS packages.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed Nov 17 2021 Qiayuan Liao <liaoqiayuan@gmail.com> - 0.1.1-2
- Autogenerated by Bloom

